import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { connect, createInstruction, readVerified, Transaction, SystemProgram, deriveSkill } from '../scripts/client.mjs';
import { loadPayload } from '../scripts/payload.mjs';
import { marketAddress, programDataAddress, offerAddress, licenseAddress, readLicense, buyInstruction, bn, LICENSE_BYTES } from '../scripts/commerce.mjs';
const { Keypair } = createRequire(import.meta.url)('@solana/web3.js');

test('model 00: authority, exact payments, independent licenses, duplicate and atomic rollback', async () => {
  const { program, provider, connection } = await connect({ local: true });
  const admin = provider.wallet.publicKey;
  const [creator, treasury, a, b, poor, outsider, rollback] = Array.from({ length: 7 }, () => Keypair.generate());
  const rent = await connection.getMinimumBalanceForRentExemption(LICENSE_BYTES);
  const price = 100000001;
  await provider.sendAndConfirm(new Transaction().add(...[creator, treasury, a, b, outsider, rollback].map(k => SystemProgram.transfer({ fromPubkey: admin, toPubkey: k.publicKey, lamports: 1000000000 })), SystemProgram.transfer({ fromPubkey: admin, toPubkey: poor.publicKey, lamports: rent + 60000000 })));
  const original = loadPayload();
  const skill = deriveSkill(program.programId, creator.publicKey, original.payloadHash);
  await provider.sendAndConfirm(new Transaction().add(await createInstruction(program, creator.publicKey, original)), [creator]);
  const market = marketAddress(program);
  const marketAccounts = signer => ({ market, admin: signer, program: program.programId, programData: programDataAddress(program), systemProgram: SystemProgram.programId });
  await assert.rejects(() => program.methods.initializeMarket(treasury.publicKey, 5000).accountsStrict(marketAccounts(outsider.publicKey)).signers([outsider]).rpc(), error => error.error?.errorCode?.code === 'UnauthorizedAdmin');
  assert.equal(await connection.getAccountInfo(market), null);
  await assert.rejects(() => program.methods.initializeMarket(treasury.publicKey, 10001).accountsStrict(marketAccounts(admin)).rpc(), error => error.error?.errorCode?.code === 'InvalidFee');
  assert.equal(await connection.getAccountInfo(market), null);
  await program.methods.initializeMarket(treasury.publicKey, 5000).accountsStrict(marketAccounts(admin)).rpc();
  await assert.rejects(() => program.methods.initializeMarket(outsider.publicKey, 0).accountsStrict(marketAccounts(admin)).rpc());
  const offer = offerAddress(program, skill);
  const offerAccounts = signer => ({ market, skill, offer, creator: signer, systemProgram: SystemProgram.programId });
  await assert.rejects(() => program.methods.createOffer(bn(price)).accountsStrict(offerAccounts(outsider.publicKey)).signers([outsider]).rpc(), error => error.error?.errorCode?.code === 'UnauthorizedCreator');
  assert.equal(await connection.getAccountInfo(offer), null);
  await assert.rejects(() => program.methods.createOffer(bn(0)).accountsStrict(offerAccounts(creator.publicKey)).signers([creator]).rpc(), error => error.error?.errorCode?.code === 'InvalidPrice');
  await program.methods.createOffer(bn(price)).accountsStrict(offerAccounts(creator.publicKey)).signers([creator]).rpc();
  await assert.rejects(() => program.methods.createOffer(bn(1)).accountsStrict(offerAccounts(creator.publicKey)).signers([creator]).rpc());
  assert.equal((await readLicense(program, b.publicKey, skill)).license, null);
  const balances = async () => Promise.all([creator, treasury].map(k => connection.getBalance(k.publicKey)));
  const before = await balances();
  const buyerBefore = await connection.getBalance(a.publicKey);
  await provider.sendAndConfirm(new Transaction().add(await buyInstruction(program, a.publicKey, skill, price)), [a]);
  const after = await balances();
  assert.deepEqual(after.map((v, i) => v - before[i]), [50000001, 50000000]);
  assert.equal(buyerBefore - await connection.getBalance(a.publicKey), price + rent, 'Admin pays network fee, buyer pays price and license rent');
  const licenseA = await readLicense(program, a.publicKey, skill);
  assert.ok(licenseA.license);
  assert.equal((await connection.getAccountInfo(licenseA.address)).data.length, LICENSE_BYTES);
  const duplicateBalances = await balances();
  await assert.rejects(async () => provider.sendAndConfirm(new Transaction().add(await buyInstruction(program, a.publicKey, skill, price)), [a]));
  assert.deepEqual(await balances(), duplicateBalances);
  await provider.sendAndConfirm(new Transaction().add(await buyInstruction(program, b.publicKey, skill, price)), [b]);
  const licenseB = await readLicense(program, b.publicKey, skill);
  assert.ok(licenseB.license);
  assert.ok(!licenseA.address.equals(licenseB.address));

  const buyAccounts = buyer => ({ market, skill, offer, license: licenseAddress(program, buyer, skill), buyer, creator: creator.publicKey, treasury: treasury.publicKey, systemProgram: SystemProgram.programId });
  const stable = await balances();
  await assert.rejects(() => program.methods.buyLicense(bn(price - 1)).accountsStrict(buyAccounts(outsider.publicKey)).signers([outsider]).rpc(), error => error.error?.errorCode?.code === 'PriceLimit');
  await assert.rejects(() => program.methods.buyLicense(bn(price)).accountsStrict({ ...buyAccounts(outsider.publicKey), treasury: a.publicKey }).signers([outsider]).rpc(), error => error.error?.errorCode?.code === 'ConstraintAddress');
  await assert.rejects(() => program.methods.buyLicense(bn(price)).accountsStrict({ ...buyAccounts(outsider.publicKey), creator: a.publicKey }).signers([outsider]).rpc());
  await assert.rejects(() => program.methods.buyLicense(bn(price)).accountsStrict(buyAccounts(creator.publicKey)).signers([creator]).rpc(), error => error.error?.errorCode?.code === 'BuyerIsRecipient');
  const poorBalance = await connection.getBalance(poor.publicKey);
  await assert.rejects(async () => provider.sendAndConfirm(new Transaction().add(await buyInstruction(program, poor.publicKey, skill, price)), [poor], { skipPreflight: true }));
  const failedPayment = await connection.getParsedTransaction((await connection.getSignaturesForAddress(poor.publicKey))[0].signature, { maxSupportedTransactionVersion: 0 });
  assert.ok(failedPayment.meta.err);
  assert.equal(failedPayment.meta.err.InstructionError[0], 0);
  const transfers = failedPayment.meta.innerInstructions.flatMap(group => group.instructions).filter(ix => ix.parsed?.type === 'transfer');
  assert.equal(transfers[0].parsed.info.destination, creator.publicKey.toBase58());
  assert.equal(transfers[0].parsed.info.lamports, 50000001);
  assert.equal(transfers[1].parsed.info.destination, treasury.publicKey.toBase58());
  assert.equal(transfers[1].parsed.info.lamports, 50000000);
  assert.equal(await connection.getBalance(poor.publicKey), poorBalance);
  assert.equal(await connection.getAccountInfo(licenseAddress(program, poor.publicKey, skill)), null);
  // First CPI has sufficient funds; second CPI fails. Neither payment survives.
  assert.deepEqual(await balances(), stable);
  const rollbackBalance = await connection.getBalance(rollback.publicKey);
  const tx = new Transaction().add(await buyInstruction(program, rollback.publicKey, skill, price), SystemProgram.transfer({ fromPubkey: rollback.publicKey, toPubkey: treasury.publicKey, lamports: 2000000000 }));
  await assert.rejects(() => provider.sendAndConfirm(tx, [rollback], { skipPreflight: true }));
  const failedAfterBuy = await connection.getParsedTransaction((await connection.getSignaturesForAddress(rollback.publicKey))[0].signature, { maxSupportedTransactionVersion: 0 });
  assert.equal(failedAfterBuy.meta.err.InstructionError[0], 1);
  assert.ok(failedAfterBuy.meta.logMessages.includes(`Program ${program.programId} success`));
  assert.equal(await connection.getBalance(rollback.publicKey), rollbackBalance);
  assert.equal(await connection.getAccountInfo(licenseAddress(program, rollback.publicKey, skill)), null);
  assert.equal(await connection.getAccountInfo(licenseAddress(program, outsider.publicKey, skill)), null);
  assert.deepEqual(await balances(), stable);
  const { recovered } = await readVerified(program, creator.publicKey, original);
  assert.deepEqual(recovered, original.payload, 'Skill remains byte-identical after commerce operations');
});
