/* Generated by tools/generate_pinmap.py; edit hardware/pinmap.json. */
#pragma once
#define JR_PINMAP_REVISION "JRBOT-HW-03"
#define JR_GPIO_BLOCKED(p) (((p)==21) || ((p)==41) || ((p)==42) || ((p)==47))
#define JR_OLED_SDA_GPIO 1
_Static_assert(!JR_GPIO_BLOCKED(JR_OLED_SDA_GPIO), "Reserved GPIO: JR_OLED_SDA_GPIO");
#define JR_OLED_SCL_GPIO 2
_Static_assert(!JR_GPIO_BLOCKED(JR_OLED_SCL_GPIO), "Reserved GPIO: JR_OLED_SCL_GPIO");
#define JR_CAM_PWDN -1
#define JR_CAM_RESET -1
#define JR_CAM_XCLK 15
_Static_assert(!JR_GPIO_BLOCKED(JR_CAM_XCLK), "Reserved GPIO: JR_CAM_XCLK");
#define JR_CAM_SDA 4
_Static_assert(!JR_GPIO_BLOCKED(JR_CAM_SDA), "Reserved GPIO: JR_CAM_SDA");
#define JR_CAM_SCL 5
_Static_assert(!JR_GPIO_BLOCKED(JR_CAM_SCL), "Reserved GPIO: JR_CAM_SCL");
#define JR_CAM_D0 11
_Static_assert(!JR_GPIO_BLOCKED(JR_CAM_D0), "Reserved GPIO: JR_CAM_D0");
#define JR_CAM_D1 9
_Static_assert(!JR_GPIO_BLOCKED(JR_CAM_D1), "Reserved GPIO: JR_CAM_D1");
#define JR_CAM_D2 8
_Static_assert(!JR_GPIO_BLOCKED(JR_CAM_D2), "Reserved GPIO: JR_CAM_D2");
#define JR_CAM_D3 10
_Static_assert(!JR_GPIO_BLOCKED(JR_CAM_D3), "Reserved GPIO: JR_CAM_D3");
#define JR_CAM_D4 12
_Static_assert(!JR_GPIO_BLOCKED(JR_CAM_D4), "Reserved GPIO: JR_CAM_D4");
#define JR_CAM_D5 18
_Static_assert(!JR_GPIO_BLOCKED(JR_CAM_D5), "Reserved GPIO: JR_CAM_D5");
#define JR_CAM_D6 17
_Static_assert(!JR_GPIO_BLOCKED(JR_CAM_D6), "Reserved GPIO: JR_CAM_D6");
#define JR_CAM_D7 16
_Static_assert(!JR_GPIO_BLOCKED(JR_CAM_D7), "Reserved GPIO: JR_CAM_D7");
#define JR_CAM_VSYNC 6
_Static_assert(!JR_GPIO_BLOCKED(JR_CAM_VSYNC), "Reserved GPIO: JR_CAM_VSYNC");
#define JR_CAM_HREF 7
_Static_assert(!JR_GPIO_BLOCKED(JR_CAM_HREF), "Reserved GPIO: JR_CAM_HREF");
#define JR_CAM_PCLK 13
_Static_assert(!JR_GPIO_BLOCKED(JR_CAM_PCLK), "Reserved GPIO: JR_CAM_PCLK");
