/* Generated by tools/generate_pinmap.py; edit hardware/pinmap.json. */
#pragma once
#define JR_PINMAP_REVISION "JRBOT-HW-04"
#define JR_CAMERA_MODEL "OV5640"
#define JR_MIC_MODEL "MS3625"
#define JR_MIC_INTERFACE_I2S 1
#define JR_OLED_SDA_GPIO 1
#define JR_OLED_SCL_GPIO 2
#define JR_CAM_PWDN -1
#define JR_CAM_RESET -1
#define JR_CAM_XCLK 15
#define JR_CAM_SDA 4
#define JR_CAM_SCL 5
#define JR_CAM_D0 11
#define JR_CAM_D1 9
#define JR_CAM_D2 8
#define JR_CAM_D3 10
#define JR_CAM_D4 12
#define JR_CAM_D5 18
#define JR_CAM_D6 17
#define JR_CAM_D7 16
#define JR_CAM_VSYNC 6
#define JR_CAM_HREF 7
#define JR_CAM_PCLK 13
#define JR_AUDIO_BCLK_GPIO 21
#define JR_AUDIO_LRC_GPIO 47
#define JR_AUDIO_DIN_GPIO 42
#define JR_MIC_SCK_GPIO 21
#define JR_MIC_WS_GPIO 47
#define JR_MIC_SD_GPIO 41
_Static_assert(JR_AUDIO_BCLK_GPIO == JR_MIC_SCK_GPIO, "BCLK/SCK must be shared");
_Static_assert(JR_AUDIO_LRC_GPIO == JR_MIC_WS_GPIO, "WS must be shared");
_Static_assert(JR_AUDIO_DIN_GPIO != JR_MIC_SD_GPIO, "I2S TX/RX data pins must differ");
_Static_assert(JR_OLED_SDA_GPIO == 1 && JR_OLED_SCL_GPIO == 2, "OLED must remain on GPIO1/2");
