'use strict';
const FIRMWARE_PREFIX='JRBotV2_';
const faces=[['Neutro','neutro'],['Feliz','feliz'],['Triste','triste'],['Animado','animado'],['Bravo','bravo'],['Surpreso','surpreso'],['Pensando','pensando'],['Cetico','cetico'],['Sono','sono'],['Confuso','confuso'],['Piscando','piscando'],['Amor','amor'],['Brincalhao','brincalhao'],['Preocupado','preocupado'],['Cool','cool'],['Bateria','bateria']];
const el=id=>document.getElementById(id), val=id=>el(id).value.trim();
const logEl=el('log');
let serverCursor=0, serverSession='', autoScroll=true, busy=false, device=null;
let mode='serial', serialConnected=false, activePort='';
let logMode='essential';
function compactStatus(raw){const f=fields(raw);return 'STATUS face='+(f.expression||'?')+' mic='+(f.mic||'?')+(f.mic_owner&&f.mic_owner!=='none'?'('+f.mic_owner+')':'')+' audio='+(f.audio_last||'not_run')+' voice='+(f.voice_running||'0')+' p='+(f.voice_probability||'0')+'/'+(f.voice_min_probability||'0')+' wifi='+(f.wifi||'?')+' ip='+(f.ip||'?');}
function compactApi(raw){try{const obj=JSON.parse(raw.slice(7)),r=obj.result||{};let extra='';if(Object.prototype.hasOwnProperty.call(r,'state'))extra=' state='+r.state+' samples='+(r.samples??'?')+' detections='+(r.detections??'?')+' avg='+(typeof r.avg_probability==='number'?r.avg_probability.toFixed(3):'?')+' last='+(typeof r.last_probability==='number'?r.last_probability.toFixed(3):'?');else if(r.api)extra=' api='+r.api+' playground='+(r.playground?'1':'0');else if(r.path)extra=' '+r.path;return 'API id='+(obj.id||'-')+' ok='+(obj.ok?'1':'0')+extra;}catch(e){return raw;}}
function compactLogLine(raw){if(raw.startsWith('JR_STATUS '))return compactStatus(raw);if(raw.startsWith('JR_API '))return compactApi(raw);const brain=raw.indexOf('JR_BRAIN ');if(brain>=0)return raw.slice(brain);const voice=raw.indexOf('jrbot_voice: ');if(voice>=0)return 'VOICE '+raw.slice(voice+'jrbot_voice: '.length);const audio=raw.indexOf('jrbot_audio: ');if(audio>=0)return 'AUDIO '+raw.slice(audio+'jrbot_audio: '.length);return raw;}
function noisyLogLine(raw){if(/^JR_REPLY .* (JR_STATUS|JR_API) /.test(raw))return true;if(/jrbot_voice: name sample /.test(raw))return true;if(/^Build fst from commands\./.test(raw)||/^Quantized MultiNet6/.test(raw))return true;if(/^I \(\d+\) (s3 ll_cam|cam_hal|sccb-ng|ov\d+|camera|MODEL_LOADER|wifi:<)/.test(raw))return true;return false;}
function renderLogNode(node){const raw=node.dataset.raw||'',ts=node.dataset.ts||'';const hide=logMode==='essential'&&node.dataset.noise==='1';node.style.display=hide?'none':'block';node.textContent='['+ts+'] '+(logMode==='raw'?raw:compactLogLine(raw));}
function appendLog(items){for(const item of items){const line=document.createElement('div');line.dataset.raw=item.line;line.dataset.ts=item.ts;line.dataset.noise=noisyLogLine(item.line)?'1':'0';renderLogNode(line);logEl.appendChild(line);el('last').textContent=item.ts;}while(logEl.children.length>1200)logEl.removeChild(logEl.firstChild);if(autoScroll)logEl.scrollTop=logEl.scrollHeight;}
function localLine(line){appendLog([{ts:new Date().toLocaleTimeString(),line}]);}
function clearLog(){logEl.textContent='';}
function downloadLog(){const blob=new Blob([Array.from(logEl.children,n=>'['+(n.dataset.ts||'')+'] '+(n.dataset.raw||n.textContent)).join('\n')],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='JrBot-painel-log.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function toggleLogMode(){logMode=logMode==='essential'?'raw':'essential';for(const node of logEl.children)renderLogNode(node);const b=el('log_mode_toggle');if(b)b.textContent=logMode==='essential'?'Ver log bruto':'Ver log essencial';if(autoScroll)logEl.scrollTop=logEl.scrollHeight;}
function installLogModeToggle(){if(el('log_mode_toggle'))return;const heading=logEl.previousElementSibling;if(!heading)return;let holder=heading.querySelector('span');if(!holder){holder=document.createElement('span');heading.appendChild(holder);}const b=document.createElement('button');b.id='log_mode_toggle';b.className='gray';b.textContent='Ver log bruto';b.onclick=toggleLogMode;holder.insertBefore(b,holder.firstChild);}
function openWifiConfig(){el('wifi_config_title').scrollIntoView({behavior:'smooth'});}
function connection(text,ok){el('conn').textContent=text;el('conn').className='pill '+(ok?'ok':'bad');}
function fields(text){const result={};for(const token of text.trim().split(/\s+/)){const at=token.indexOf('=');if(at>0)result[token.slice(0,at)]=token.slice(at+1);}return result;}
function currentFirmware(){return !!device&&typeof device.version==='string'&&device.version.startsWith(FIRMWARE_PREFIX)&&device.hardware==='JRBOT-HW-04';}
function oledAvailable(){return !!device&&device.oled_presence==='available'&&['ready','degraded'].includes(device.oled);}
function refreshControls(){
  document.querySelectorAll('[data-action]').forEach(b=>b.disabled=busy);
  const valid=currentFirmware(),voiceBusy=device?.voice_running==='1';
  el('test_audio').disabled=busy||!valid||voiceBusy||!['ready','on_demand'].includes(device?.audio);
  el('test_camera').disabled=busy||!valid||mode!=='serial'||device?.camera!=='available';
  el('test_mic').disabled=busy||!valid||voiceBusy||['busy','error'].includes(device?.mic);
  document.querySelectorAll('#faces button,#demo').forEach(b=>b.disabled=busy||!valid||!oledAvailable());
  el('audio_volume').disabled=busy||!valid;
  el('apply_volume').disabled=busy||!valid;
}
function invalidate(message){device=null;el('device_msg').textContent=message;for(const id of ['fw_version','fw_profile','oled_state','audio_state','camera_state','mic_state'])el(id).textContent='Nao verificado';refreshControls();}
function renderStatus(text){
  if(!text.startsWith('JR_STATUS protocol=2 ')){invalidate('Firmware sem protocolo V2.');connection('Firmware nao confirmado',false);throw new Error('Firmware sem protocolo V2.');}
  const next=fields(text);if(!next.version||!next.profile||!next.hardware){invalidate('Estado incompleto.');connection('Firmware nao confirmado',false);throw new Error('Estado incompleto do firmware.');}
  device=next;const valid=currentFirmware(),voiceBusy=next.voice_running==='1';
  el('face_controls').open=oledAvailable();
  el('fw_version').textContent=next.version;
  el('fw_profile').textContent=next.profile;
  el('oled_state').textContent=next.oled_presence==='available'?'Disponivel - '+next.oled:'Indisponivel - '+(next.oled||'offline');
  const audioSeq=Number(next.audio_test_seq||0),audioBytes=Number(next.audio_last_bytes||0);
  el('audio_state').textContent=!valid?'Firmware antigo/incompativel':voiceBusy?'Em uso pela voz - teste manual bloqueado':next.audio_test_running==='1'?'Teste em andamento':audioSeq>0?'Ultimo teste #'+audioSeq+' - '+(next.audio_last||'?')+' - '+audioBytes+' bytes':'Pronto para teste - MAX98357A';
  el('camera_state').textContent=next.camera==='available'?'Disponivel - OV5640 '+(next.camera_pid||''):'Indisponivel - OV5640';
  if(next.mic==='available')el('mic_state').textContent='Disponivel - MS3625 confirmado';
  else if(next.mic==='busy')el('mic_state').textContent='Em uso - '+(next.mic_owner||'I2S');
  else if(next.mic==='unknown')el('mic_state').textContent='Indefinido - execute Testar microfone ou Gravar 3s';
  else el('mic_state').textContent='Erro - MS3625 ('+(next.mic_error||'desconhecido')+')';
  if(/^\d+$/.test(next.volume||'')){el('audio_volume').value=next.volume;el('audioVolText').textContent=next.volume+'%';}
  el('device_msg').textContent='Estado atualizado. Build: '+(next.build_sp||next.version)+'.'+(voiceBusy?' Voz/I2S ativo; testes manuais de audio e microfone ficam bloqueados.':'')+(next.pending_restart==='1'?' Wi-Fi pendente de reinicializacao.':'');
  el('audio_msg').textContent=voiceBusy?'Audio reservado pelo modo de voz. Desative autonomo ou pare o Playground antes do teste manual.':audioSeq>0?'Diagnostico do audio: teste #'+audioSeq+', resultado '+(next.audio_last||'?')+', '+audioBytes+' bytes transmitidos.':'MAX98357A pronto. O teste manual so roda com o I2S livre.';
  el('cam_msg').textContent=next.camera==='available'?'OV5640 detectada. Teste liberado.':'OV5640 nao respondeu. Conecte e clique Atualizar estado.';
  el('face_msg').textContent=oledAvailable()?'OLED respondeu. Controles liberados.':'OLED nao respondeu; o restante do JrBot continua disponivel.';
  const micInfo=el('test_mic')?.nextElementSibling;if(micInfo)micInfo.textContent=next.mic==='available'?'MS3625 ja foi confirmado por sinal real.':next.mic==='busy'?'MS3625 esta em uso por '+(next.mic_owner||'I2S')+'.':next.mic==='unknown'?'Estado inicial indefinido. Use Testar microfone ou Gravar 3s para confirmar.':'Falha de I/O: '+(next.mic_error||'desconhecida')+'.';
  connection(valid?(mode==='serial'?'Painel conectado em '+(activePort||'Serial')+' - firmware confirmado':'Wi-Fi - firmware confirmado'):'Firmware nao confirmado',valid);
  refreshControls();
}
async function api(path,opts={}){const headers={...(opts.headers||{})};if(opts.method==='POST')headers['X-JrBot-Panel']='1';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),35000);try{const r=await fetch(path,{...opts,headers,signal:controller.signal});const text=await r.text();if(!r.ok)throw new Error(text||('HTTP '+r.status));return text;}catch(e){if(e.name==='AbortError')throw new Error('Tempo de resposta esgotado.');throw e;}finally{clearTimeout(timer);}}
async function action(work,messageId='device_msg'){if(busy)return;busy=true;refreshControls();try{return await work();}catch(e){el(messageId).textContent='Erro: '+e.message;localLine('ERRO: '+e.message);}finally{busy=false;refreshControls();}}
async function setMode(m){if(busy)return;mode=m==='wifi'?'wifi':'serial';document.querySelector('input[value='+mode+']').checked=true;el('lbl_serial').classList.toggle('active',mode==='serial');el('lbl_wifi').classList.toggle('active',mode==='wifi');el('serialbar').classList.toggle('show',mode==='serial');el('wifibar').classList.toggle('show',mode==='wifi');invalidate('Selecione a conexao e clique em Conectar ou Atualizar estado.');connection('Conexao nao verificada',false);if(mode==='wifi'){await api('/disconnect',{method:'POST'});serialConnected=false;activePort='';localStorage.setItem('jr_esp_ip',val('esp_ip'));}}
async function refreshPorts(){try{const j=JSON.parse(await api('/ports'));const available=[...new Set((j.ports||[]).filter(p=>/^COM\d+$/i.test(p)).map(p=>p.toUpperCase()))].sort((a,b)=>Number(a.slice(3))-Number(b.slice(3)));const previous=(val('port')||localStorage.getItem('jr_serial_port')||'').toUpperCase();el('port').textContent='';if(!available.length){const o=document.createElement('option');o.value='';o.textContent='Nenhuma porta COM detectada';el('port').appendChild(o);return;}for(const p of available){const o=document.createElement('option');o.value=p;o.textContent=p;el('port').appendChild(o);}el('port').value=available.includes(previous)?previous:available[0];}catch(e){localLine('ERRO: '+e.message);}}
async function connect(){return action(async()=>{const port=val('port').toUpperCase();if(!/^COM\d+$/.test(port))throw new Error('Selecione uma porta COM detectada e clique Atualizar portas.');invalidate('Abrindo '+port+' e consultando o firmware...');const t=await api('/connect',{method:'POST',body:new URLSearchParams({port})});serialConnected=true;activePort=port;localStorage.setItem('jr_serial_port',port);connection('Porta aberta; consultando firmware',false);localLine(t);await new Promise(resolve=>setTimeout(resolve,1200));await send('status');});}
async function disconnect(){return action(async()=>{await api('/disconnect',{method:'POST'});serialConnected=false;activePort='';invalidate('Desconectado.');connection('Desconectado',false);});}
async function send(command){const verb=command.trim().toLowerCase().split(/\s+/)[0];if(['audio_test','som','beep','mic_test'].includes(verb)&&!currentFirmware())throw new Error('Teste bloqueado: grave uma versao JRBotV2_ / HW04.');if(new TextEncoder().encode(command).length>768)throw new Error('Comando excede 768 bytes.');let t;try{t=await api('/send',{method:'POST',body:new URLSearchParams({command,mode,ip:val('esp_ip')})});}catch(e){if(command.trim().toLowerCase()==='status'){connection('Firmware sem confirmacao',false);}throw e;}if(t.trim())localLine(t.trim());if(command.trim().toLowerCase()==='status')renderStatus(t);if(mode==='wifi')localStorage.setItem('jr_esp_ip',val('esp_ip'));return t;}
async function refreshStatus(){return action(()=>send('status'));}
async function checkVersion(){return action(async()=>{await send('status');el('device_msg').textContent='Firmware confirmado: '+device.version+' | '+device.hardware+' | '+device.profile;});}
async function sendCustom(){const c=el('custom').value;if(c.trim())return action(()=>send(c));}
async function connectWifi(){if(busy)return;await setMode('wifi');return refreshStatus();}
async function testWifi(){return connectWifi();}
async function setAudioVolume(){return action(async()=>{const v=val('audio_volume');el('audioVolText').textContent=v+'%';const t=await send('audio_volume '+v);if(fields(t).audio_volume!==v)throw new Error('Volume nao confirmado.');if(device)device.volume=v;el('audio_msg').textContent='Volume confirmado: '+v+'%.';},'audio_msg');}
async function testAudio(){return action(async()=>{if(!currentFirmware()||!['ready','on_demand'].includes(device.audio))throw new Error('Audio nao disponivel.');if(device?.voice_running==='1')throw new Error('I2S em uso pela voz. Desative autonomo ou pare o Playground.');el('audio_msg').textContent='Executando um unico teste I2S com o volume aplicado...';const reply=await send('audio_test'),f=fields(reply);if(f.audio_test!=='tx_completed')throw new Error('Teste de audio nao confirmado.');el('audio_msg').textContent='I2S confirmado: teste #'+(f.seq||'?')+', '+(f.bytes||'?')+' bytes, '+(f.freq||'?')+' Hz.';},'audio_msg');}
async function testMic(){return action(async()=>{if(!currentFirmware())throw new Error('Firmware nao confirmado.');if(device?.voice_running==='1'||device?.mic==='busy')throw new Error('Microfone em uso pela voz/Playground.');if(device?.mic==='error')throw new Error('Microfone em erro de I/O: '+(device?.mic_error||'?'));el('mic_state').textContent='Testando MS3625...';const reply=await send('mic_test'),f=fields(reply);if(f.mic_test!=='signal_detected')throw new Error('Sinal do microfone nao confirmado. Tente novamente falando perto do microfone.');el('mic_state').textContent='OK - MS3625 confirmado | amostras '+f.samples+' | pico '+f.peak_raw+' | mudancas '+f.changes;if(device){device.mic='available';device.mic_confirmed='1';}},'device_msg');}
async function testCamera(){return action(async()=>{if(mode!=='serial')throw new Error('Use Serial USB na porta COM selecionada para testar a camera.');if(!device||device.camera!=='available')throw new Error('Camera nao detectada. Clique Atualizar estado.');el('cam_msg').textContent='Capturando um quadro da OV5640...';const t=await send('camera_test'),f=fields(t);if(f.camera_test!=='frame_received'||f.released!=='1')throw new Error('Captura nao confirmada.');el('cam_msg').textContent='OK - quadro '+f.width+' x '+f.height+', '+f.bytes+' bytes, sensor '+f.pid+'.';},'cam_msg');}
function takePhoto(){el('cam_msg').textContent='Use Testar camera para verificar a captura.';}function openCameraPortal(){takePhoto();}
function saveWifiLocal(){for(const id of ['wifi_ssid','wifi_host','wifi_static','wifi_ip','wifi_gw','wifi_mask','wifi_dns1','wifi_dns2','esp_ip'])localStorage.setItem('jr_'+id,el(id).value);}
function loadWifiLocal(){for(const id of ['wifi_ssid','wifi_host','wifi_static','wifi_ip','wifi_gw','wifi_mask','wifi_dns1','wifi_dns2','esp_ip']){const v=localStorage.getItem('jr_'+id);if(v!==null)el(id).value=v;}}
function encodedField(id,max){const text=el(id).value;if(/[\x00-\x1f\x7f]/.test(text))throw new Error('Caracteres de controle nao permitidos.');if(new TextEncoder().encode(text).length>max)throw new Error(id+' excede '+max+' bytes.');return encodeURIComponent(text);}
async function configureWifi(){return action(async()=>{if(mode!=='serial')throw new Error('Use Serial USB antes de salvar Wi-Fi.');const ssid=encodedField('wifi_ssid',32);if(!ssid)throw new Error('Informe o SSID.');const pairs=[['ssid',ssid],['pass',encodedField('wifi_pass',64)],['host',encodedField('wifi_host',32)],['static',val('wifi_static')],['ip',encodedField('wifi_ip',15)],['gw',encodedField('wifi_gw',15)],['mask',encodedField('wifi_mask',15)],['dns1',encodedField('wifi_dns1',15)],['dns2',encodedField('wifi_dns2',15)]];const reply=await send('wifi_config_pct '+pairs.map(([k,v])=>k+'='+v).join('|'));if(!reply.startsWith('JR_WIFI_SALVO'))throw new Error('Salvamento nao confirmado.');saveWifiLocal();el('wifi_pass').value='';el('device_msg').textContent='Wi-Fi salvo. Reinicie a placa e clique Atualizar estado.';});}
async function clearWifi(){if(confirm('Limpar configuracao Wi-Fi?'))return action(async()=>{if(mode!=='serial')throw new Error('Use Serial USB.');await send('wifi_clear');el('device_msg').textContent='Configuracao Wi-Fi limpa. Reinicie a placa.';});}
async function poll(){try{const j=JSON.parse(await api('/logs?after='+serverCursor+'&session='+encodeURIComponent(serverSession)));if(serverSession&&serverSession!==j.session){serverCursor=0;invalidate('Servidor reiniciado. Reconecte.');}serverSession=j.session;if(j.gap)localLine('Aviso: registros antigos expiraram.');appendLog(j.logs);serverCursor=j.next_cursor;if(mode==='serial'&&!busy){serialConnected=j.serial_connected;activePort=j.serial_port||'';if(!serialConnected){if(device)invalidate('Serial desconectada.');connection('Serial desconectado',false);}else if(!device)connection('Porta aberta; firmware nao confirmado',false);}}catch(e){if(!busy){connection('Servidor indisponivel',false);}}finally{setTimeout(poll,600);}}
for(const [name,command] of faces){const b=document.createElement('button');b.className='face';b.textContent=name;b.onclick=()=>action(()=>send(command));el('faces').appendChild(b);}
const micButton=el('test_mic');if(micButton){micButton.textContent='Testar microfone';micButton.className='green';micButton.onclick=()=>testMic();if(micButton.nextElementSibling)micButton.nextElementSibling.textContent='MS3625 inicia como indefinido; confirme com teste real. Durante voz/Playground o I2S aparece em uso.';}
el('custom').addEventListener('keydown',e=>{if(e.key==='Enter')sendCustom();});logEl.addEventListener('scroll',()=>{autoScroll=logEl.scrollTop+logEl.clientHeight>=logEl.scrollHeight-20;});window.addEventListener('unhandledrejection',event=>{event.preventDefault();localLine('ERRO: '+String(event.reason?.message||event.reason));});
const sub=document.querySelector('header .sub');if(sub)sub.textContent='JrBot V2 | log essencial por padrao | log bruto disponivel';
if(el('brain_msg'))el('brain_msg').textContent='Modo autonomo: somente JR BOT / J R BOT. Confianca minima atual: 0.60. Deteccoes abaixo disso sao rejeitadas sem mudar a face ou falar.';
installLogModeToggle();loadWifiLocal();setMode('serial').catch(e=>localLine('ERRO: '+e.message));refreshPorts();poll();refreshControls();