idf_component_register(
    SRCS
        "main.c"
        "../core/jr_wifi.c"
        "../core/jr_commands.c"
        "../core/jr_usb_terminal.c"
        "../module_face/jr_face.c"
        "../module_portal/jr_portal.c"
        "../module_camera/jr_camera_diag.c"
        "../module_audio/jr_audio.c"
        "../module_audio/jr_mic.c"
        "../module_brain/jr_brain.c"
        "../module_brain/jr_voice.c"
        "../module_brain/jr_reply_audio.c"
        "../module_playground/jr_playground.c"
        "../module_runtime/jr_runtime_api.c"
    INCLUDE_DIRS
        "."
        "../core"
        "../module_face"
        "../module_portal"
        "../module_camera"
        "../module_audio"
        "../module_brain"
        "../module_playground"
        "../module_runtime"
    REQUIRES esp_driver_i2c esp_driver_uart esp_driver_usb_serial_jtag esp_driver_gpio esp_driver_i2s esp_wifi esp_event esp_netif esp_http_server esp_psram esp32-camera esp-sr nvs_flash log esp_timer heap json
)
