(function(){'use strict';
const PROGRAM='Ax11PmTRcz3NLBSxtLm38Aush3MY5GJoBjyjggjtS454',GENESIS='EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG',RPC='https://api.devnet.solana.com',B58='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
const DISC_LICENSE='f898c364b96cb0e7',DISC_SKILL='350df2cc4df901d7',DISC_LICENSE_B58='iahantz4EVL';
const FACES=['neutral','happy','sad','excited','angry','surprised','thinking','skeptical','sleepy','confused','winking','love','playful','worried','cool','battery_low'];
const RECIPE={v:1,run:[['face','surprised'],['wait',500],['face','thinking'],['wait',500],['face','happy'],['wait',500]]};
let wallet=null,address='',authenticated=false,networkOk=false,skills=[],selected='',busy=false,bound=false;
const q=id=>document.getElementById(id);
const eq=(a,b)=>a.length===b.length&&a.every((v,i)=>v===b[i]);
const hex=b=>Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');
function b64(s){const x=atob(s),b=new Uint8Array(x.length);for(let i=0;i<x.length;i++)b[i]=x.charCodeAt(i);return b;}
function b58e(bytes){let d=[0];for(const byte of bytes){let c=byte;for(let j=0;j<d.length;j++){c+=d[j]<<8;d[j]=c%58;c=(c/58)|0;}while(c){d.push(c%58);c=(c/58)|0;}}let s='';for(let i=0;i<bytes.length&&bytes[i]===0;i++)s+='1';for(let i=d.length-1;i>=0;i--)s+=B58[d[i]];return s;}
function b58d(text){let b=[0];for(const ch of text){const p=B58.indexOf(ch);if(p<0)throw Error('Endereco base58 invalido');let c=p;for(let j=0;j<b.length;j++){c+=b[j]*58;b[j]=c&255;c>>=8;}while(c){b.push(c&255);c>>=8;}}for(let i=0;i<text.length-1&&text[i]==='1';i++)b.push(0);return new Uint8Array(b.reverse());}
function u32(b,o){return (b[o]|b[o+1]<<8|b[o+2]<<16|b[o+3]<<24)>>>0;}
function msg(t,err=false){const x=q('jrskill-app-msg');if(x){x.textContent=t;x.style.color=err?'#ff8585':'#9fb1ca';}}
function clearSkills(){skills=[];selected='';const s=q('jrskill-app-select');if(s)s.replaceChildren(new Option('Nenhuma Skill carregada',''));const d=q('jrskill-app-selected');if(d)d.textContent='Nenhuma Skill selecionada';}
function render(){const w=q('jrskill-app-wallet'),n=q('jrskill-app-network');if(w)w.textContent=authenticated?'Wallet autenticada':address?'Wallet conectada':'Wallet desconectada';if(n)n.textContent=networkOk?'Devnet confirmada':'Devnet nao confirmada';if(w)w.style.color=authenticated?'#63d99b':'#9fb1ca';if(n)n.style.color=networkOk?'#63d99b':'#9fb1ca';if(q('jrskill-app-address'))q('jrskill-app-address').textContent=address||'Nenhum endereco conectado';q('jrskill-app-auth').disabled=!address||busy;q('jrskill-app-net').disabled=!authenticated||busy;q('jrskill-app-search').disabled=!authenticated||!networkOk||busy;q('jrskill-app-select-btn').disabled=!skills.length||busy;q('jrskill-app-run').disabled=!selected||!authenticated||!networkOk||busy;q('jrskill-app-disconnect').disabled=!address||busy;}
async function rpc(method,params,timeout=15000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(RPC,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),cache:'no-store',signal:c.signal});if(!r.ok)throw Error('RPC HTTP '+r.status);const j=await r.json();if(j.error)throw Error(j.error.message||'Erro RPC');return j.result;}finally{clearTimeout(timer);}}
function provider(){return window.phantom&&window.phantom.solana?window.phantom.solana:(window.solana&&window.solana.isPhantom?window.solana:null);}
function resetAuth(){authenticated=false;networkOk=false;clearSkills();render();}
function bind(){if(!wallet||bound||typeof wallet.on!=='function')return;bound=true;wallet.on('disconnect',()=>{address='';resetAuth();msg('Wallet desconectada.');});wallet.on('accountChanged',pk=>{const next=pk&&pk.toString?pk.toString():'';if(next!==address){address=next;resetAuth();msg(next?'Conta alterada. Autentique novamente.':'Wallet desconectada.');}});}
async function connect(){if(busy)return;busy=true;render();try{wallet=provider();if(!wallet)throw Error('Phantom nao detectada neste navegador');const r=await wallet.connect();address=(r&&r.publicKey?r.publicKey:wallet.publicKey).toString();if(b58d(address).length!==32)throw Error('Endereco Solana invalido');bind();resetAuth();msg('Wallet conectada. Clique Autenticar carteira.');}catch(e){msg('Falha ao conectar: '+e.message,true);}finally{busy=false;render();}}
async function auth(){if(!wallet||!address||busy)return;busy=true;render();try{const nonce=crypto.randomUUID?crypto.randomUUID():String(Date.now())+'-'+Math.random().toString(36).slice(2),text='JrBot - autenticar carteira\nOrigem: '+location.origin+'\nCarteira: '+address+'\nAmbiente: solana:devnet\nNonce: '+nonce+'\nEsta assinatura autentica somente a sessao local do App JrBot.\nNao autoriza compra ou transferencia de SOL.',bytes=new TextEncoder().encode(text),signed=await wallet.signMessage(bytes,'utf8'),sig=new Uint8Array(signed.signature),raw=b58d(address);if(sig.length!==64||raw.length!==32)throw Error('Assinatura/endereco invalido');let key;try{key=await crypto.subtle.importKey('raw',raw,{name:'Ed25519'},false,['verify']);}catch(_){throw Error('Navegador sem verificacao Ed25519 WebCrypto');}if(!await crypto.subtle.verify({name:'Ed25519'},key,sig,bytes))throw Error('Assinatura nao confere com a wallet');authenticated=true;networkOk=false;clearSkills();msg('Wallet autenticada. Agora verifique a Devnet.');}catch(e){authenticated=false;msg('Autenticacao nao confirmada: '+e.message,true);}finally{busy=false;render();}}
async function checkNetwork(){if(!authenticated||busy)return;busy=true;render();try{if(await rpc('getGenesisHash',[])!==GENESIS)throw Error('RPC nao e Solana Devnet');const b=await rpc('getBalance',[address,{commitment:'finalized'}]);if(!b||typeof b.value!=='number')throw Error('Saldo Devnet invalido');networkOk=true;const sol=(b.value/1e9).toFixed(9).replace(/0+$/,'').replace(/\.$/,'');q('jrskill-app-balance').textContent='Saldo Devnet: '+(sol||'0')+' SOL de teste';msg('Solana Devnet confirmada.');}catch(e){networkOk=false;msg('Devnet nao confirmada: '+e.message,true);}finally{busy=false;render();}}
function account(row,disc,size){if(!row||!row.account||row.account.owner!==PROGRAM||!Array.isArray(row.account.data))throw Error('Conta Solana invalida');const b=b64(row.account.data[0]);if(b.length!==size||hex(b.slice(0,8))!==disc)throw Error('Layout da conta invalido');return b;}
async function discover(apply=true){if(!authenticated||!networkOk)throw Error('Wallet autenticada e Devnet confirmada sao obrigatorias');const buyer=b58d(address),r=await rpc('getProgramAccounts',[PROGRAM,{encoding:'base64',commitment:'finalized',withContext:true,filters:[{dataSize:137},{memcmp:{offset:0,bytes:DISC_LICENSE_B58}},{memcmp:{offset:9,bytes:address}}]}],20000);if(!r||!Array.isArray(r.value)||r.value.length>32)throw Error('Resposta de licencas invalida');const ls=[];for(const row of r.value){const b=account(row,DISC_LICENSE,137);if(b[8]!==0||!eq(b.slice(9,41),buyer))throw Error('Licenca nao pertence a wallet');ls.push({license:row.pubkey,skill:b58e(b.slice(41,73)),offer:b58e(b.slice(73,105))});}const out=[];if(ls.length){const a=await rpc('getMultipleAccounts',[ls.map(x=>x.skill),{encoding:'base64',commitment:'finalized'}],20000);if(!a||!Array.isArray(a.value)||a.value.length!==ls.length)throw Error('Resposta de Skills invalida');for(let i=0;i<ls.length;i++){const row={account:a.value[i]},sb=account(row,DISC_SKILL,589),schema=sb[40],digest=sb.slice(41,73),len=u32(sb,73);if(schema!==1||len<1||len>512)throw Error('Schema/tamanho da Skill invalido');const payload=sb.slice(77,77+len),hash=new Uint8Array(await crypto.subtle.digest('SHA-256',payload));if(!eq(hash,digest))throw Error('Hash da Skill invalido');let doc;try{doc=JSON.parse(new TextDecoder().decode(payload));}catch(_){throw Error('Payload JrSkill nao e JSON valido');}if(!doc||doc.v!==1||!Array.isArray(doc.run)||doc.run.length<1||doc.run.length>64)throw Error('JrSkill v1 invalida');out.push({...ls[i],name:ls[i].skill==='8LRRfZVnyjSYPLezJBCdGriwVcbzsopogZBDTAFSFJux'?'minimal_recipe_01':'Skill '+ls[i].skill.slice(0,8),hash:hex(digest),bytes:len,doc});}}
if(apply){skills=out;const s=q('jrskill-app-select');s.replaceChildren();if(!out.length)s.append(new Option('Nenhuma Skill licenciada',''));for(const x of out)s.append(new Option(x.name+' - licenciada',x.skill));if(selected&&!out.some(x=>x.skill===selected))selected='';msg(out.length?out.length+' Skill(s) licenciada(s) encontrada(s).':'Nenhuma Skill licenciada encontrada.');render();}return out;}
async function search(){if(busy)return;busy=true;render();try{await discover(true);}catch(e){clearSkills();msg('Busca de Skills falhou: '+e.message,true);}finally{busy=false;render();}}
function choose(){const skill=skills.find(x=>x.skill===q('jrskill-app-select').value);if(!skill){selected='';render();return;}selected=skill.skill;q('jrskill-app-selected').textContent=skill.name+' | '+skill.bytes+' bytes | hash '+skill.hash.slice(0,12)+'...';msg('Skill selecionada: '+skill.name);render();}
async function fresh(skill){if(!authenticated||!address)throw Error('Wallet nao autenticada');const r=await rpc('getAccountInfo',[skill.license,{encoding:'base64',commitment:'finalized'}]);if(!r||!r.value)throw Error('Licenca nao encontrada');const b=account({account:r.value},DISC_LICENSE,137);if(b[8]!==0||!eq(b.slice(9,41),b58d(address))||b58e(b.slice(41,73))!==skill.skill)throw Error('Licenca nao corresponde a wallet/Skill');}
async function command(obj){const r=await fetch('/cmd',{method:'POST',headers:{'Content-Type':'text/plain','X-JrBot-Command':'1'},body:'api '+JSON.stringify(obj),cache:'no-store'}),t=await r.text();if(!r.ok)throw Error(t);if(!t.startsWith('JR_API '))throw Error('Resposta Runtime API invalida');const j=JSON.parse(t.slice(7));if(j.ok!==true)throw Error(JSON.stringify(j.error||{}));return j;}
function validateDoc(doc,depth=0){if(depth>4||!doc||doc.v!==1||!Array.isArray(doc.run)||doc.run.length<1||doc.run.length>64)throw Error('Skill/Recipe fora dos limites');for(const call of doc.run){if(!Array.isArray(call)||call.length!==2)throw Error('Chamada JrSkill invalida');const [fn,v]=call;if(fn==='face'){if(!FACES.includes(v))throw Error('Face nao permitida: '+v);}else if(fn==='wait'){if(!Number.isInteger(v)||v<0||v>5000)throw Error('wait invalido');}else if(fn==='recipe'){if(v!=='face_sequence')throw Error('Recipe nao instalada no App');validateDoc(RECIPE,depth+1);}else throw Error('Funcao JrSkill nao suportada: '+fn);}}
async function execDoc(doc,skill,depth){if(depth>4||!doc||doc.v!==1||!Array.isArray(doc.run)||doc.run.length<1||doc.run.length>64)throw Error('Skill/Recipe fora dos limites');for(const call of doc.run){if(!Array.isArray(call)||call.length!==2)throw Error('Chamada JrSkill invalida');const fn=call[0],v=call[1];if(fn==='wait'){if(!Number.isInteger(v)||v<0||v>5000)throw Error('wait invalido');await new Promise(r=>setTimeout(r,v));continue;}if(fn==='recipe'){if(v!=='face_sequence')throw Error('Recipe nao instalada no App');await execDoc(RECIPE,skill,depth+1);continue;}if(fn==='face'){if(!FACES.includes(v))throw Error('Face nao permitida nesta versao');await fresh(skill);const a=await command({v:1,fn:'face',args:{expression:v}});if(a.result&&a.result.expression!==v)throw Error('Runtime API nao confirmou face '+v);continue;}throw Error('Funcao JrSkill nao suportada: '+fn);}}
async function run(){if(busy||!selected)return;busy=true;render();try{const latest=await discover(false),skill=latest.find(x=>x.skill===selected);if(!skill)throw Error('Licenca da Skill selecionada nao foi confirmada');validateDoc(skill.doc);await fresh(skill);const cap=await command({v:1,fn:'capabilities',args:{}});if(!cap.result||!Array.isArray(cap.result.actions)||!cap.result.actions.includes('face'))throw Error('Firmware sem capability face');msg('Executando '+skill.name+' no JrBot...');await execDoc(skill.doc,skill,0);msg('Skill concluida no JrBot: result=ok');}catch(e){msg('Execucao interrompida: '+e.message,true);}finally{busy=false;render();}}
async function disconnect(){if(busy)return;busy=true;render();try{if(wallet&&typeof wallet.disconnect==='function')await wallet.disconnect();}catch(_){}address='';authenticated=false;networkOk=false;clearSkills();busy=false;render();msg('Wallet desconectada.');}
function build(){if(q('jrskill-app-board'))return;const feedback=q('feedback');if(!feedback)return;const card=document.createElement('section');card.id='jrskill-app-board';card.className='card';card.innerHTML="<h2>Minhas Skills</h2><div class='row'><span id='jrskill-app-wallet' class='pill'>Wallet desconectada</span><span id='jrskill-app-network' class='pill'>Devnet nao confirmada</span></div><div id='jrskill-app-address' class='state' style='user-select:all'>Nenhum endereco conectado</div><div class='row' style='margin-top:10px'><button id='jrskill-app-connect' class='primary grow'>Conectar carteira</button><button id='jrskill-app-auth' class='grow' disabled>Autenticar carteira</button><button id='jrskill-app-net' class='grow' disabled>Verificar Devnet</button></div><div id='jrskill-app-balance' class='state'>Saldo Devnet: nao consultado</div><div class='row' style='margin-top:10px'><button id='jrskill-app-search' class='grow' disabled>Buscar minhas Skills</button><select id='jrskill-app-select' class='grow'><option value=''>Nenhuma Skill carregada</option></select><button id='jrskill-app-select-btn' class='grow' disabled>Selecionar Skill</button></div><div id='jrskill-app-selected' class='state'>Nenhuma Skill selecionada</div><div class='row' style='margin-top:10px'><button id='jrskill-app-run' class='primary grow' disabled>Executar Skill no JrBot</button><button id='jrskill-app-disconnect' class='grow' disabled>Desconectar wallet</button></div><div id='jrskill-app-msg' class='state'>Conecte a wallet para carregar suas Skills licenciadas. Compras ficam fora do App.</div><div class='hint'>Wallet + Devnet + Minhas Skills + execucao. A compra sera feita na Store web. O painel de desenvolvimento continua separado.</div>";feedback.parentNode.insertBefore(card,feedback);q('jrskill-app-connect').onclick=connect;q('jrskill-app-auth').onclick=auth;q('jrskill-app-net').onclick=checkNetwork;q('jrskill-app-search').onclick=search;q('jrskill-app-select-btn').onclick=choose;q('jrskill-app-run').onclick=run;q('jrskill-app-disconnect').onclick=disconnect;render();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();