#!/usr/bin/env python3
"""Generate fixed pin definitions and documentation from the hardware manifest."""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]

def outputs(data):
    required = {21, 41, 42, 47}
    blocked = set(data['blocked_by_owner'])
    if not required.issubset(blocked):
        raise ValueError('Owner-reserved GPIOs must not be removed')
    groups = [data['oled'], data['camera']]
    assigned = [pin for group in groups for pin in group.values() if pin >= 0]
    if len(assigned) != len(set(assigned)) or blocked.intersection(assigned):
        raise ValueError('Fixed GPIO collision')
    if data['oled'] != {'SDA': 1, 'SCL': 2}:
        raise ValueError('OLED pinout must remain SDA=1 SCL=2')
    protected = set(assigned) | blocked
    for key in ('usb_native', 'uart0', 'memory_reserved', 'boot_reserved'):
        if protected.intersection(data[key]):
            raise ValueError('Fixed map overlaps protected resources: ' + key)
        protected.update(data[key])
    if any(value is not None for key, value in data['audio'].items() if key != 'status'):
        raise ValueError('Audio wires must be assigned in local Kconfig, not in the manifest')
    pins = {f'JR_OLED_{key}_GPIO': pin for key, pin in data['oled'].items()}
    pins.update({f'JR_CAM_{key}': pin for key, pin in data['camera'].items()})
    h = ['/* Generated by tools/generate_pinmap.py; edit hardware/pinmap.json. */', '#pragma once',
         f'#define JR_PINMAP_REVISION "{data["revision"]}"',
         '#define JR_GPIO_BLOCKED(p) (' + ' || '.join(f'((p)=={p})' for p in sorted(blocked)) + ')']
    for name, pin in pins.items():
        h.append(f'#define {name} {pin}')
        if pin >= 0:
            h.append(f'_Static_assert(!JR_GPIO_BLOCKED({name}), "Reserved GPIO: {name}");')
    d = ['# JrBot - pinagem HW03', '', '<!-- Generated by tools/generate_pinmap.py. -->',
         '**Fonte unica dos pinos fixos:** `hardware/pinmap.json`. Numeros sao GPIOs, nao posicoes do conector.', '',
         '**GPIO21, GPIO41, GPIO42 e GPIO47 ja estao ocupados.** Manter as ligacoes existentes. Funcao de cada um ainda nao informada; nao dirigir esses pinos com novos modulos.', '',
         '## Ligacoes fixas do projeto', '', '| Modulo | Sinal | GPIO | Estado |', '|---|---|---:|---|']
    for title, key in [('OLED', 'oled'), ('Camera', 'camera')]:
        for signal, pin in data[key].items():
            state = 'Sem GPIO controlado' if pin < 0 else ('Reservado; OLED desligado no perfil atual' if key == 'oled' else 'Mapa herdado; confirmar conector da placa')
            d.append(f'| {title} | {signal} | {pin} | {state} |')
    d += ['', '## Inventario completo de GPIOs', '', '| GPIOs | Uso / restricao |', '|---|---|',
          '| 0, 3, 45, 46 | Configuracao de boot; nao realocar nesta revisao |',
          '| 1, 2 | OLED SDA/SCL; reservados mesmo sem display |',
          '| 4-13, 15-18 | Camera, conforme tabela acima |',
          '| 14, 38 | Candidatos; verificar exposicao, microSD e demais circuitos |',
          '| 19, 20 | USB nativa; nao reutilizar |',
          '| 21, 41, 42, 47 | Ocupados informados pelo proprietario; nao reutilizar |',
          '| 22-25 | Nao sao GPIOs disponiveis do ESP32-S3 |',
          '| 26-37 | Reservados por politica para flash/PSRAM, incluindo OPI |',
          '| 39, 40 | Candidatos; tambem relacionados a JTAG externo |',
          '| 43, 44 | UART0, terminal/painel via USB-UART nesta montagem |',
          '| 48 | Candidato; pode estar ligado a LED RGB da placa |', '',
          'A lista de candidatos NAO e uma lista de pinos fisicamente livres. O fabricante e a revisao exatos da placa continuam pendentes.', '',
          '## Amplificador - mapa anterior revogado', '',
          'Nenhum GPIO de audio e atribuido por padrao: BCLK=-1, WS=-1, DOUT=-1. A aprovacao antiga nao habilita HW03.', '',
          '| Opcao SOMENTE para conferir na placa | BCLK | WS/LRC | ESP32 DOUT -> DIN do amplificador |',
          '|---|---:|---:|---:|', '| Proposta, nao ativada | 39 | 40 | 14 |', '',
          'Nao ligar seguindo a proposta sem conferir a ocupacao fisica. Selecionar tres GPIOs distintos e preencher a nova configuracao somente apos verificar os tres fios. Se nao estiverem livres, manter -1.', '',
          '## Recursos internos', '',
          '| Recurso | Reserva |', '|---|---|', '| I2C0 | OLED; nao inicializado em modo sem OLED |',
          '| I2C1 | SCCB da camera; driver I2C novo |', '| I2S TX | Amplificador sob demanda; nenhum RX de microfone implementado |',
          '| LEDC timer 0 / canal 0 | Clock da camera |', '| Servo | Sem GPIO/timer atribuido |', '',
          'Microfone: modelo, interface e sinais pendentes. Os quatro GPIOs ocupados nao foram associados a um modulo por suposicao.', '',
          'Veja [esquema completo e pendencias](ESQUEMA_LIGACAO.md), [materiais](MATERIAIS.md) e [fontes tecnicas](FONTES.md).', '']
    return {'firmware/core/jr_pinmap_fixed.h': '\n'.join(h)+'\n', 'docs/PINAGEM.md': '\n'.join(d)}

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = json.loads((ROOT/'hardware/pinmap.json').read_text(encoding='utf-8'))
    bad=[]
    for path, text in outputs(data).items():
        dest=ROOT/path
        if args.check:
            if not dest.exists() or dest.read_text(encoding='utf-8') != text:
                bad.append(path)
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(text, encoding='utf-8', newline='\n')
    if bad:
        print('Divergencia: ' + ', '.join(bad), file=sys.stderr)
        return 1
    print('Pinmap HW03: ' + ('sincronizado' if args.check else 'gerado'))
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
