#!/usr/bin/env python3
"""Validate JrBot HW04 pin map and generate the firmware fixed-pin header."""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'hardware' / 'pinmap.json'
HEADER = ROOT / 'firmware' / 'core' / 'jr_pinmap_fixed.h'


def validate(data):
    if data.get('revision') != 'JRBOT-HW-04':
        raise ValueError('Expected JRBOT-HW-04')
    if data.get('camera_model') != 'OV5640':
        raise ValueError('Camera model must be OV5640 for HW04')
    if data['oled']['SDA'] != 1 or data['oled']['SCL'] != 2:
        raise ValueError('OLED must remain SDA=1 SCL=2')
    audio = data['audio']
    mic = data['microphone']
    if (audio['BCLK'], audio['WS'], audio['DOUT']) != (21, 47, 42):
        raise ValueError('HW04 amplifier map must be BCLK=21 WS=47 DOUT=42')
    if (mic['SCK'], mic['WS'], mic['SD']) != (21, 47, 41):
        raise ValueError('HW04 microphone map must be SCK=21 WS=47 SD=41')
    if mic.get('interface') != 'I2S' or mic.get('model') != 'MS3625':
        raise ValueError('HW04 microphone must be MS3625 I2S')
    if audio.get('amplifier') != 'MAX98357A':
        raise ValueError('HW04 amplifier must be MAX98357A')
    if audio['BCLK'] != mic['SCK'] or audio['WS'] != mic['WS']:
        raise ValueError('I2S BCLK/WS must be shared')
    if len({audio['BCLK'], audio['WS'], audio['DOUT'], mic['SD']}) != 4:
        raise ValueError('HW04 audio data/clock pins must resolve to four distinct GPIOs')

    fixed = [p for p in data['oled'].values() if isinstance(p, int) and p >= 0]
    fixed += [p for p in data['camera'].values() if isinstance(p, int) and p >= 0]
    if len(fixed) != len(set(fixed)):
        raise ValueError('OLED/camera GPIO collision')
    protected = set(fixed)
    for key in ('usb_native', 'uart0', 'memory_reserved', 'boot_reserved'):
        group = set(data[key])
        if protected.intersection(group):
            raise ValueError('Fixed map overlaps protected resources: ' + key)
        protected.update(group)
    for pin in (21, 47, 42, 41):
        if pin in protected:
            raise ValueError(f'Audio GPIO {pin} overlaps another JrBot resource')


def header_text(data):
    c = data['camera']
    return f'''/* Generated by tools/generate_pinmap.py; edit hardware/pinmap.json. */
#pragma once
#define JR_PINMAP_REVISION "{data['revision']}"
#define JR_CAMERA_MODEL "{data['camera_model']}"
#define JR_MIC_MODEL "{data['microphone']['model']}"
#define JR_MIC_INTERFACE_I2S 1
#define JR_OLED_SDA_GPIO {data['oled']['SDA']}
#define JR_OLED_SCL_GPIO {data['oled']['SCL']}
#define JR_CAM_PWDN {c['PWDN']}
#define JR_CAM_RESET {c['RESET']}
#define JR_CAM_XCLK {c['XCLK']}
#define JR_CAM_SDA {c['SDA']}
#define JR_CAM_SCL {c['SCL']}
#define JR_CAM_D0 {c['D0']}
#define JR_CAM_D1 {c['D1']}
#define JR_CAM_D2 {c['D2']}
#define JR_CAM_D3 {c['D3']}
#define JR_CAM_D4 {c['D4']}
#define JR_CAM_D5 {c['D5']}
#define JR_CAM_D6 {c['D6']}
#define JR_CAM_D7 {c['D7']}
#define JR_CAM_VSYNC {c['VSYNC']}
#define JR_CAM_HREF {c['HREF']}
#define JR_CAM_PCLK {c['PCLK']}
#define JR_AUDIO_BCLK_GPIO {data['audio']['BCLK']}
#define JR_AUDIO_LRC_GPIO {data['audio']['WS']}
#define JR_AUDIO_DIN_GPIO {data['audio']['DOUT']}
#define JR_MIC_SCK_GPIO {data['microphone']['SCK']}
#define JR_MIC_WS_GPIO {data['microphone']['WS']}
#define JR_MIC_SD_GPIO {data['microphone']['SD']}
_Static_assert(JR_AUDIO_BCLK_GPIO == JR_MIC_SCK_GPIO, "BCLK/SCK must be shared");
_Static_assert(JR_AUDIO_LRC_GPIO == JR_MIC_WS_GPIO, "WS must be shared");
_Static_assert(JR_AUDIO_DIN_GPIO != JR_MIC_SD_GPIO, "I2S TX/RX data pins must differ");
_Static_assert(JR_OLED_SDA_GPIO == 1 && JR_OLED_SCL_GPIO == 2, "OLED must remain on GPIO1/2");
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = json.loads(MANIFEST.read_text(encoding='utf-8'))
    validate(data)
    expected = header_text(data)
    if args.check:
        if not HEADER.exists() or HEADER.read_text(encoding='utf-8') != expected:
            print('Divergencia: firmware/core/jr_pinmap_fixed.h', file=sys.stderr)
            return 1
        print('Pinmap HW04: sincronizado')
        return 0
    HEADER.write_text(expected, encoding='utf-8', newline='\n')
    print('Pinmap HW04: gerado')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
