#pragma once

static const char JR_HTTPS_TEST_HTML[] =
"<!doctype html><html lang='pt-br'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>JrBot HTTPS EXP</title><style>body{font:16px system-ui;background:#0b1020;color:#eef4ff;margin:0;padding:20px}main{max-width:720px;margin:auto}.card{background:#151d31;border:1px solid #30405f;border-radius:16px;padding:16px;margin:12px 0}button{background:#243454;color:white;border:1px solid #48628f;border-radius:10px;padding:12px 16px;font:inherit}pre{white-space:pre-wrap;word-break:break-word;background:#090e19;padding:12px;border-radius:10px}audio{width:100%;margin-top:12px}.ok{color:#72e6a6}.bad{color:#ff9090}</style></head><body><main>"
"<h1>JrBot HTTPS EXP 01</h1><div class='card'><b>Diagnostico do navegador</b><pre id='diag'></pre><button id='refresh'>Atualizar diagnostico</button></div>"
"<div class='card'><b>Teste do microfone</b><p id='state'>Ainda nao testado.</p><button id='mic'>Gravar 3 segundos</button><audio id='preview' controls hidden></audio><pre id='err'></pre></div>"
"<div class='card'>Depois que este teste mostrar <b>Secure Context = SIM</b> e o microfone gravar, abra <code>/</code> pelo mesmo HTTPS e teste o fluxo completo de mensagem para o JrBot.</div>"
"<script>const q=id=>document.getElementById(id);let stream=null,rec=null,chunks=[];function yn(v){return v?'SIM':'NAO'}function diag(){const md=!!navigator.mediaDevices,gm=!!(navigator.mediaDevices&&navigator.mediaDevices.getUserMedia),mr=!!window.MediaRecorder,ac=!!(window.AudioContext||window.webkitAudioContext);q('diag').textContent=['URL: '+location.href,'Protocolo: '+location.protocol,'Secure Context: '+yn(window.isSecureContext),'mediaDevices: '+yn(md),'getUserMedia: '+yn(gm),'MediaRecorder: '+yn(mr),'AudioContext: '+yn(ac),'User agent: '+navigator.userAgent].join('\n');q('diag').className=window.isSecureContext&&gm&&mr?'ok':'bad'}q('refresh').onclick=diag;async function testMic(){q('err').textContent='';q('preview').hidden=true;if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){q('state').textContent='getUserMedia indisponivel.';diag();return}if(!window.MediaRecorder){q('state').textContent='MediaRecorder indisponivel.';diag();return}try{q('state').textContent='Solicitando permissao...';stream=await navigator.mediaDevices.getUserMedia({audio:true,video:false});chunks=[];rec=new MediaRecorder(stream);rec.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data)};rec.onstop=()=>{const type=rec&&rec.mimeType?rec.mimeType:'audio/webm',blob=new Blob(chunks,{type});for(const t of stream.getTracks())t.stop();stream=null;const url=URL.createObjectURL(blob);q('preview').src=url;q('preview').hidden=false;q('state').textContent='Gravacao concluida. Ouça o preview.';diag()};rec.start();q('state').textContent='Gravando por 3 segundos...';setTimeout(()=>{if(rec&&rec.state==='recording')rec.stop()},3000)}catch(e){if(stream){for(const t of stream.getTracks())t.stop();stream=null}q('state').textContent='Falha ao acessar o microfone.';q('err').textContent='Erro: '+(e&&e.name?e.name+': ':'')+(e&&e.message?e.message:String(e));diag()}}q('mic').onclick=testMic;diag();</script></main></body></html>";
