#pragma once

static const char JR_HTTPS_TEST_HTML[] =
"<!doctype html><html lang='pt-br'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>JrBot HTTPS EXP</title><style>body{font:16px system-ui;background:#0b1020;color:#eef4ff;margin:0;padding:20px}main{max-width:720px;margin:auto}.card{background:#151d31;border:1px solid #30405f;border-radius:16px;padding:16px;margin:12px 0}button{background:#243454;color:white;border:1px solid #48628f;border-radius:10px;padding:12px 16px;font:inherit}pre{white-space:pre-wrap;word-break:break-word;background:#090e19;padding:12px;border-radius:10px;min-height:40px}audio{width:100%;margin-top:12px}.ok{color:#72e6a6}.bad{color:#ff9090}.warn{color:#ffd77a}</style></head><body><main>"
"<h1>JrBot HTTPS EXP 02</h1><div class='card'><b>Diagnostico do navegador</b><pre id='diag' class='warn'>JavaScript ainda nao executou.</pre><button id='refresh'>Atualizar diagnostico</button></div>"
"<div class='card'><b>Teste do microfone</b><p id='state'>Ainda nao testado.</p><button id='mic'>Gravar 3 segundos</button><audio id='preview' controls hidden></audio><pre id='err'>Sem erro registrado.</pre></div>"
"<div class='card'>Objetivo: certificado confiavel + <b>Secure Context = SIM</b> + <b>getUserMedia = SIM</b>. Se o navegador mostrar Nao seguro, instale e confie na CA local gerada pelo instalador antes de testar o microfone.</div>"
"<script>(function(){var q=function(id){return document.getElementById(id)};var stream=null;var rec=null;var chunks=[];function yn(v){return v?'SIM':'NAO'}function setDiag(){try{var md=!!navigator.mediaDevices;var gm=!!(navigator.mediaDevices&&navigator.mediaDevices.getUserMedia);var mr=!!window.MediaRecorder;var ac=!!(window.AudioContext||window.webkitAudioContext);var lines=['JavaScript: SIM','URL: '+location.href,'Protocolo: '+location.protocol,'Secure Context: '+yn(window.isSecureContext),'mediaDevices: '+yn(md),'getUserMedia: '+yn(gm),'MediaRecorder: '+yn(mr),'AudioContext: '+yn(ac),'User agent: '+navigator.userAgent];q('diag').textContent=lines.join('\n');q('diag').className=window.isSecureContext&&gm&&mr?'ok':'bad'}catch(e){q('diag').textContent='Falha no diagnostico JavaScript: '+String(e);q('diag').className='bad'}}function stopTracks(){if(stream&&stream.getTracks){var tracks=stream.getTracks();for(var i=0;i<tracks.length;i++)tracks[i].stop()}stream=null}function testMic(){q('err').textContent='Sem erro registrado.';q('preview').hidden=true;setDiag();if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){q('state').textContent='getUserMedia indisponivel. Verifique Secure Context/certificado.';return}if(!window.MediaRecorder){q('state').textContent='MediaRecorder indisponivel.';return}q('state').textContent='Solicitando permissao...';navigator.mediaDevices.getUserMedia({audio:true,video:false}).then(function(s){stream=s;chunks=[];rec=new MediaRecorder(stream);rec.ondataavailable=function(e){if(e.data&&e.data.size)chunks.push(e.data)};rec.onstop=function(){var type=rec&&rec.mimeType?rec.mimeType:'audio/webm';var blob=new Blob(chunks,{type:type});stopTracks();q('preview').src=URL.createObjectURL(blob);q('preview').hidden=false;q('state').textContent='Gravacao concluida. Ouça o preview.';setDiag()};rec.onerror=function(e){q('err').textContent='MediaRecorder error: '+String(e&&e.error?e.error:e);stopTracks()};rec.start();q('state').textContent='Gravando por 3 segundos...';setTimeout(function(){if(rec&&rec.state==='recording')rec.stop()},3000)}).catch(function(e){stopTracks();q('state').textContent='Falha ao acessar o microfone.';q('err').textContent='Erro: '+(e&&e.name?e.name+': ':'')+(e&&e.message?e.message:String(e));setDiag()})}window.addEventListener('load',function(){q('refresh').onclick=setDiag;q('mic').onclick=testMic;setDiag()})})();</script></main></body></html>";
